#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Do not edit this file, this is handled by Salt and your changes will be lost.

# Copyright (c) 2013, Bruno Clermont
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# Author: Bruno Clermont <patate@fastmail.cn>
# Maintainer: Bruno Clermont <patate@fastmail.cn>
#             Quan Tong Anh <tonganhquan.net@gmail.com>

"""
RavenMail: Emulate /usr/bin/mail(x) but send mail to a Sentry server instead.
"""

import sys
import os

import pysc


class Mail(pysc.Application):
    """
    Send an email
    """
    def get_argument_parser(self):
        argp = super(Mail, self).get_argument_parser()
        argp.add_argument('-s', '--subject', help="Subject")
        argp.add_argument('extra_args', nargs='*')
        return argp

    def main(self):
        # consume standard input early
        body = os.linesep.join(sys.stdin.readlines())
        if not len(body):
            sys.stderr.write("Empty stdin, nothing to report")
            sys.stderr.write(os.linesep)
            sys.exit(1)

        # init raven quickly, so if something is wrong it get logged early
        from raven import Client
        dsn = self.config['sentry_dsn']
        if not dsn.startswith("requests+"):
            dsn = "requests+" + dsn
        client = Client(dsn=dsn)

        if self.config['subject']:
            msg = os.linesep.join((self.config['subject'], body))
        else:
            msg = body
        client.captureMessage(msg, extra=os.environ)

if __name__ == "__main__":
    Mail().run()
