postgresql
----------

Check :doc:`/postgresql/doc/index` connection.

Critical: if unable to connect.

postgresql_encoding
-------------------

Check if :doc:`/postgresql/doc/index` database encoding is UTF8 or
not.

Critical: if unable to connect or database encoding is not UTF8

postgresql_empty
----------------

Check if :doc:`/postgresql/doc/index` database is empty or not.

Critical: if unable to connect or there is no tables in database.

