Process resources data for |deployment| locate in
os > process > |deployment| in graphite web interface.

cpu_times:system
----------------

Total time in seconds |deployment| process spent in kernel mode.

cpu_times:user
--------------

Total time in seconds |deployment| process spent in user mode.

io_counters:read_count
----------------------

Number of times |deployment| process made a read operation.

io_counters:write_count
-----------------------

Number of times |deployment| process made a write operation.

io_counters: read_bytes
-----------------------

Total amount of data |deployment| process has read presents in bytes.

io_counters: write_bytes
------------------------

Total amount of data |deployment| process has written presents in bytes.

num_ctx_switches:involuntary
----------------------------

The number involuntary context switches performed by |deployment| process.

num_ctx_switches:voluntary
--------------------------

The number voluntary context switches performed by |deployment| process.

cpu_percent
-----------

|deployment| process CPU utilization as a percentage.

memory_percent
--------------

|deployment| process memory utilization as a percentage.

num_threads
-----------

The number of threads currently used by |deployment| process.
